version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  app:
    depends_on:
      - db
    build: .
    volumes:
      - "./magento:/var/www/html"
    ports:
      - "80:80"
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
