version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  app:
    depends_on:
      - db
    build:
      context: "."
      dockerfile: "Dockerfile.app"
    volumes:
      - "./magento:/var/www/html"
    ports:
      - "8080:8080"
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

  varnish:
    build:
      context: "."
      dockerfile: "Dockerfile.varnish"
    ports:
      - "80:80"
